services:
  email-parser:
    build:
      context: ./email-parser
      dockerfile: Dockerfile
    volumes:
      - ./email-parser:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - phishing-net
    ports:
      - "5001:5000"

  phishing-detector:
    build:
      context: ./phishing-detector
      dockerfile: Dockerfile
    volumes:
      - ./phishing-detector:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - phishing-net
    ports:
      - "5002:5000"

  link-analyzer:
    build:
      context: ./link-analyzer
      dockerfile: Dockerfile
    volumes:
      - ./link-analyzer:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - phishing-net
    ports:
      - "5003:5000"

  verdict-service:
    build:
      context: ./verdict-service
      dockerfile: Dockerfile
    volumes:
      - ./verdict-service:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - phishing-net
    ports:
      - "5004:5000"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./gateway:/app
    networks:
      - phishing-net
    ports:
      - "5000:5000"
    depends_on:
      - email-parser
      - phishing-detector
      - link-analyzer
      - verdict-service

  website:
    build:
      context: ../website
      dockerfile: Dockerfile
    networks:
      - phishing-net
    environment:
      - VIRTUAL_HOST=phishing-detector.localhost
      - VIRTUAL_PORT=80
    expose:
      - "80"

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - //var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - phishing-net
    depends_on:
      - website

networks:
  phishing-net:
    driver: bridge
