# Docker Compose com Traefik (alternativa avançada)

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard do Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - phishing-net

  website:
    build:
      context: ../website
      dockerfile: Dockerfile
    networks:
      - phishing-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`phishing.local`)"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.services.website.loadbalancer.server.port=80"

  # ... resto dos serviços backend ...

networks:
  phishing-net:
    driver: bridge
